name: Cargo - Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      features:
        description: "Cargo Features"
        type: string
        default: "default"
      examples:
        description: "Run Cargo Examples"
        type: string
        default: "true"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-build.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-build.yml@main
    secrets: inherit
    with:
      features: ${{ inputs.features }}

  cargo-examples:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-examples.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-examples.yml@main
    if: ${{ inputs.examples == 'true' }}
    secrets: inherit
    needs: [ cargo-build ]
