name: Cargo - Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      package:
        description: "Cargo Package"
        required: false
        type: string
      features:
        description: "Crate Features"
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        rust-version: [ stable, beta, nightly ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: changes
        with:
          filters: |
            src:
              - '**/Cargo.*'
              - 'rust-toolchain.toml'
              - '**/*.rs'
              - '.github/workflows/*.yml'

      - name: "Setup - Rust Toolchain"
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        if: steps.changes.outputs.src == 'true'
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: "Restore cached Cargo"
        id: cache-restore
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.rust-version }}-cargo

      - name: "Build"
        if: steps.changes.outputs.src == 'true'
        run: |
          set -e

          CARGO_FEATURES="${{ inputs.features }}"
          
          if [ -n "$CARGO_FEATURES" ]; then
              echo "📦 Standard build with features: '$CARGO_FEATURES'"
              cargo build --features "$CARGO_FEATURES"
          else
              echo "📦 Standard build (default)"
              cargo build
          fi
          
          echo "📦 Disable all features"
          cargo build --no-default-features

      - name: Save Cargo / Rust Cache 
        id: cache-save
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
