name: GeekORM

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      features:
        description: "Crate Features"
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.rust-version }}
      cancel-in-progress: true

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: changes
        with:
          filters: |
            src:
              - '**/Cargo.*'
              - 'rust-toolchain.toml'
              - '**/*.rs'
              - '.github/workflows/*.yml'

      - name: "Setup - Rust Toolchain"
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        if: steps.changes.outputs.src == 'true'
        with:
          toolchain: stable

      - name: "Restore cached Cargo"
        id: cache-restore
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stable-cargo

      - name: "Install GeekORM"
        if: steps.changes.outputs.src == 'true'
        run: |
          set -e
          if ! command -v geekorm-cli >/dev/null 2>&1; then
            echo "[+] Installing GeekORM CLI"
            cargo install geekorm-cli
          else
            echo "[+] GeekORM CLI already installed..."
          fi

      - name: "Build"
        if: steps.changes.outputs.src == 'true'
        env:
          CARGO_FEATURES: ${{ inputs.features }}
        run: |
          set -e

          if [ -n "$CARGO_FEATURES" ]; then
              echo "📦 Standard build with features: '$CARGO_FEATURES'"
              cargo build --features "$CARGO_FEATURES"
          else
              echo "📦 Standard build (default)"
              cargo build
          fi
      - name: "GeekORM Migrations"
        if: steps.changes.outputs.src == 'true'
        env:
          CARGO_FEATURES: ${{ inputs.features }}
        run: |
          set -e

          geekorm-cli test
          geekorm-cli display

      - name: Save Cargo / Rust Cache 
        id: cache-save
        if: ${{ steps.changes.outputs.src == 'true' && github.event_name == 'push' }}
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
